const paises = [
  { Pais: "Selecione um Pais", Sigla: "" },
  { Pais: "Afeganistão", Sigla: "af" },
  { Pais: "África do Sul", Sigla: "za" },
  { Pais: "Albânia", Sigla: "al" },
  { Pais: "Alemanha", Sigla: "de" },
  { Pais: "Andorra", Sigla: "ad" },
  { Pais: "Angola", Sigla: "ao" },
  { Pais: "Antígua e Barbuda", Sigla: "ag" },
  { Pais: "Arábia Saudita", Sigla: "sa" },
  { Pais: "Argélia", Sigla: "dz" },
  { Pais: "Argentina", Sigla: "ar" },
  { Pais: "Armênia", Sigla: "am" },
  { Pais: "Austrália", Sigla: "au" },
  { Pais: "Áustria", Sigla: "at" },
  { Pais: "Azerbaijão", Sigla: "az" },
  { Pais: "Bahamas", Sigla: "bs" },
  { Pais: "Bahrein", Sigla: "bh" },
  { Pais: "Bangladesh", Sigla: "bd" },
  { Pais: "Barbados", Sigla: "bb" },
  { Pais: "Belarus", Sigla: "by" },
  { Pais: "Bélgica", Sigla: "be" },
  { Pais: "Belize", Sigla: "bz" },
  { Pais: "Benin", Sigla: "bj" },
  { Pais: "Bolívia", Sigla: "bo" },
  { Pais: "Bósnia e Herzegovina", Sigla: "ba" },
  { Pais: "Botsuana", Sigla: "bw" },
  { Pais: "Brasil", Sigla: "br" },
  { Pais: "Brunei", Sigla: "bn" },
  { Pais: "Bulgária", Sigla: "bg" },
  { Pais: "Burquina Faso", Sigla: "bf" },
  { Pais: "Burundi", Sigla: "bi" },
  { Pais: "Butão", Sigla: "bt" },
  { Pais: "Cabo Verde", Sigla: "cv" },
  { Pais: "Camarões", Sigla: "cm" },
  { Pais: "Camboja", Sigla: "kh" },
  { Pais: "Canadá", Sigla: "ca" },
  { Pais: "Catar", Sigla: "qa" },
  { Pais: "Cazaquistão", Sigla: "kz" },
  { Pais: "Chade", Sigla: "td" },
  { Pais: "Chile", Sigla: "cl" },
  { Pais: "China", Sigla: "cn" },
  { Pais: "Chipre", Sigla: "cy" },
  { Pais: "Cingapura", Sigla: "sg" },
  { Pais: "Colômbia", Sigla: "co" },
  { Pais: "Comores", Sigla: "km" },
  { Pais: "Congo-Brazzaville", Sigla: "cg" },
  { Pais: "Congo-Kinshasa", Sigla: "cd" },
  { Pais: "Coreia do Norte", Sigla: "kp" },
  { Pais: "Coreia do Sul", Sigla: "kr" },
  { Pais: "Costa do Marfim", Sigla: "ci" },
  { Pais: "Costa Rica", Sigla: "cr" },
  { Pais: "Croácia", Sigla: "hr" },
  { Pais: "Cuba", Sigla: "cu" },
  { Pais: "Dinamarca", Sigla: "dk" },
  { Pais: "Djibuti", Sigla: "dj" },
  { Pais: "Dominica", Sigla: "dm" },
  { Pais: "Egito", Sigla: "eg" },
  { Pais: "El Salvador", Sigla: "sv" },
  { Pais: "Emirados Árabes Unidos", Sigla: "ae" },
  { Pais: "Equador", Sigla: "ec" },
  { Pais: "Eritreia", Sigla: "er" },
  { Pais: "Eslováquia", Sigla: "sk" },
  { Pais: "Eslovênia", Sigla: "si" },
  { Pais: "Espanha", Sigla: "es" },
  { Pais: "Estados Unidos", Sigla: "us" },
  { Pais: "Estônia", Sigla: "ee" },
  { Pais: "Eswatini (Suazilândia)", Sigla: "sz" },
  { Pais: "Etiópia", Sigla: "et" },
  { Pais: "Fiji", Sigla: "fj" },
  { Pais: "Filipinas", Sigla: "ph" },
  { Pais: "Finlândia", Sigla: "fi" },
  { Pais: "França", Sigla: "fr" },
  { Pais: "Gabão", Sigla: "ga" },
  { Pais: "Gâmbia", Sigla: "gm" },
  { Pais: "Gana", Sigla: "gh" },
  { Pais: "Geórgia", Sigla: "ge" },
  { Pais: "Granada", Sigla: "gd" },
  { Pais: "Grécia", Sigla: "gr" },
  { Pais: "Guatemala", Sigla: "gt" },
  { Pais: "Guiana", Sigla: "gy" },
  { Pais: "Guiné", Sigla: "gn" },
  { Pais: "Guiné-Bissau", Sigla: "gw" },
  { Pais: "Guiné Equatorial", Sigla: "gq" },
  { Pais: "Haiti", Sigla: "ht" },
  { Pais: "Holanda", Sigla: "nl" },
  { Pais: "Honduras", Sigla: "hn" },
  { Pais: "Hungria", Sigla: "hu" },
  { Pais: "Iêmen", Sigla: "ye" },
  { Pais: "Ilhas Comores", Sigla: "km" },
  { Pais: "Ilhas Marshall", Sigla: "mh" },
  { Pais: "Ilhas Salomão", Sigla: "sb" },
  { Pais: "Índia", Sigla: "in" },
  { Pais: "Indonésia", Sigla: "id" },
  { Pais: "Irã", Sigla: "ir" },
  { Pais: "Iraque", Sigla: "iq" },
  { Pais: "Irlanda", Sigla: "ie" },
  { Pais: "Islândia", Sigla: "is" },
  { Pais: "Israel", Sigla: "il" },
  { Pais: "Itália", Sigla: "it" },
  { Pais: "Jamaica", Sigla: "jm" },
  { Pais: "Japão", Sigla: "jp" },
  { Pais: "Jordânia", Sigla: "jo" },
  { Pais: "Kosovo", Sigla: "xk" },
  { Pais: "Kuwait", Sigla: "kw" },
  { Pais: "Laos", Sigla: "la" },
  { Pais: "Lesoto", Sigla: "ls" },
  { Pais: "Letônia", Sigla: "lv" },
  { Pais: "Líbano", Sigla: "lb" },
  { Pais: "Libéria", Sigla: "lr" },
  { Pais: "Líbia", Sigla: "ly" },
  { Pais: "Liechtenstein", Sigla: "li" },
  { Pais: "Lituânia", Sigla: "lt" },
  { Pais: "Luxemburgo", Sigla: "lu" },
  { Pais: "Macedônia do Norte", Sigla: "mk" },
  { Pais: "Madagascar", Sigla: "mg" },
  { Pais: "Malásia", Sigla: "my" },
  { Pais: "Malaui", Sigla: "mw" },
  { Pais: "Maldivas", Sigla: "mv" },
  { Pais: "Mali", Sigla: "ml" },
  { Pais: "Malta", Sigla: "mt" },
  { Pais: "Marrocos", Sigla: "ma" },
  { Pais: "Maurício", Sigla: "mu" },
  { Pais: "Mauritânia", Sigla: "mr" },
  { Pais: "México", Sigla: "mx" },
  { Pais: "Mianmar (Birmânia)", Sigla: "mm" },
  { Pais: "Micronésia", Sigla: "fm" },
  { Pais: "Moçambique", Sigla: "mz" },
  { Pais: "Moldávia", Sigla: "md" },
  { Pais: "Mônaco", Sigla: "mc" },
  { Pais: "Mongólia", Sigla: "mn" },
  { Pais: "Montenegro", Sigla: "me" },
  { Pais: "Namíbia", Sigla: "na" },
  { Pais: "Nauru", Sigla: "nr" },
  { Pais: "Nepal", Sigla: "np" },
  { Pais: "Nicarágua", Sigla: "ni" },
  { Pais: "Níger", Sigla: "ne" },
  { Pais: "Nigéria", Sigla: "ng" },
  { Pais: "Niue", Sigla: "nu" },
  { Pais: "Noruega", Sigla: "no" },
  { Pais: "Nova Zelândia", Sigla: "nz" },
  { Pais: "Omã", Sigla: "om" },
  { Pais: "Palau", Sigla: "pw" },
  { Pais: "Palestina", Sigla: "ps" },
  { Pais: "Panamá", Sigla: "pa" },
  { Pais: "Papua Nova Guiné", Sigla: "pg" },
  { Pais: "Paquistão", Sigla: "pk" },
  { Pais: "Paraguai", Sigla: "py" },
  { Pais: "Peru", Sigla: "pe" },
  { Pais: "Polônia", Sigla: "pl" },
  { Pais: "Portugal", Sigla: "pt" },
  { Pais: "Quênia", Sigla: "ke" },
  { Pais: "Quirguistão", Sigla: "kg" },
  { Pais: "Reino Unido", Sigla: "gb" },
  { Pais: "República Centro-Africana", Sigla: "cf" },
  { Pais: "República Dominicana", Sigla: "do" },
  { Pais: "República Tcheca", Sigla: "cz" },
  { Pais: "Romênia", Sigla: "ro" },
  { Pais: "Ruanda", Sigla: "rw" },
  { Pais: "Rússia", Sigla: "ru" },
  { Pais: "Samoa", Sigla: "ws" },
  { Pais: "San Marino", Sigla: "sm" },
  { Pais: "Santa Lúcia", Sigla: "lc" },
  { Pais: "São Cristóvão e Nevis", Sigla: "kn" },
  { Pais: "São Tomé e Príncipe", Sigla: "st" },
  { Pais: "São Vicente e Granadinas", Sigla: "vc" },
  { Pais: "Seicheles", Sigla: "sc" },
  { Pais: "Senegal", Sigla: "sn" },
  { Pais: "Serra Leoa", Sigla: "sl" },
  { Pais: "Sérvia", Sigla: "rs" },
  { Pais: "Singapura", Sigla: "sg" },
  { Pais: "Síria", Sigla: "sy" },
  { Pais: "Somália", Sigla: "so" },
  { Pais: "Sri Lanka", Sigla: "lk" },
  { Pais: "Sudão", Sigla: "sd" },
  { Pais: "Sudão do Sul", Sigla: "ss" },
  { Pais: "Suécia", Sigla: "se" },
  { Pais: "Suíça", Sigla: "ch" },
  { Pais: "Suriname", Sigla: "sr" },
  { Pais: "Tailândia", Sigla: "th" },
  { Pais: "Taiwan", Sigla: "tw" },
  { Pais: "Tajiquistão", Sigla: "tj" },
  { Pais: "Tanzânia", Sigla: "tz" },
  { Pais: "Timor-Leste", Sigla: "tl" },
  { Pais: "Togo", Sigla: "tg" },
  { Pais: "Tonga", Sigla: "to" },
  { Pais: "Trinidad e Tobago", Sigla: "tt" },
  { Pais: "Tunísia", Sigla: "tn" },
  { Pais: "Turcomenistão", Sigla: "tm" },
  { Pais: "Turquia", Sigla: "tr" },
  { Pais: "Tuvalu", Sigla: "tv" },
  { Pais: "Ucrânia", Sigla: "ua" },
  { Pais: "Uganda", Sigla: "ug" },
  { Pais: "Uruguai", Sigla: "uy" },
  { Pais: "Uzbequistão", Sigla: "uz" },
  { Pais: "Vanuatu", Sigla: "vu" },
  { Pais: "Vaticano", Sigla: "va" },
  { Pais: "Venezuela", Sigla: "ve" },
  { Pais: "Vietnã", Sigla: "vn" },
  { Pais: "Zâmbia", Sigla: "zm" },
  { Pais: "Zimbábue", Sigla: "zw" },
];

export default paises;
